# Generated by Django 5.2.9 on 2026-01-03 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('cost_per_gram', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='g당 단가')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('bundle_size', models.IntegerField(default=3, verbose_name='묶음 단위')),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='묶음 가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalesDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='판매일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='증감량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록시간')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
                ('sales_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(verbose_name='시간(초)')),
                ('timer_type', models.CharField(choices=[('stopwatch', '스톱워치'), ('countdown', '카운트다운')], max_length=20)),
                ('started_at', models.DateTimeField(verbose_name='시작시간')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='완료시간')),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1개당 사용량(g)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
            ],
            options={
                'unique_together': {('item', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='SalesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_units', models.IntegerField(default=0, verbose_name='판매개수')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
                ('sales_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesday')),
            ],
            options={
                'unique_together': {('sales_day', 'item')},
            },
        ),
    ]
